# Generated by Django 5.2.4 on 2025-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobrecord_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecord',
            name='employment_type',
            field=models.CharField(max_length=2),
        ),
    ]
